Test Report - 2025-04-04_16-10-51
==================================================

Total Tests Run: 15
Successful: 12
Failed: 3
Errors: 0
Run Time: 0:00:00.273489

Failed Tests:
--------------------
test_file_too_large (test_app.TestImageResizerApp.test_file_too_large)
Traceback (most recent call last):
  File "/Users/ganeshbollem/Documents/image-resizer-app/tests/test_app.py", line 118, in test_file_too_large
    self.assertEqual(response.status_code, 413)
AssertionError: 400 != 413


test_convert_to_pdf_success (test_pdf.TestPDFConversion.test_convert_to_pdf_success)
Traceback (most recent call last):
  File "/Users/ganeshbollem/Documents/image-resizer-app/tests/test_pdf.py", line 149, in test_convert_to_pdf_success
    self.assertTrue(os.path.exists(pdf_path))
AssertionError: False is not true


test_convert_to_pdf_total_size_too_large (test_pdf.TestPDFConversion.test_convert_to_pdf_total_size_too_large)
Traceback (most recent call last):
  File "/Users/ganeshbollem/Documents/image-resizer-app/tests/test_pdf.py", line 121, in test_convert_to_pdf_total_size_too_large
    self.assertEqual(json_data['error'], 'Total file size exceeds limit')
AssertionError: 'File size exceeds limit' != 'Total file size exceeds limit'
- File size exceeds limit
? ^
+ Total file size exceeds limit
? ^^^^^^^



