Test Report - 2025-04-04_16-15-37
==================================================

Total Tests Run: 15
Successful: 14
Failed: 1
Errors: 0
Run Time: 0:00:00.284969

Failed Tests:
--------------------
test_file_too_large (test_app.TestImageResizerApp.test_file_too_large)
Traceback (most recent call last):
  File "/Users/ganeshbollem/Documents/image-resizer-app/tests/test_app.py", line 118, in test_file_too_large
    self.assertEqual(response.status_code, 413)
AssertionError: 400 != 413


